# Generated by Django 4.0.3 on 2022-03-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('sobrenome', models.CharField(max_length=70)),
                ('idade', models.IntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('dataNascimento', models.DateTimeField()),
                ('apelido', models.CharField(max_length=70)),
                ('observacao', models.TextField(max_length=1000)),
            ],
        ),
    ]
