# Generated by Django 4.0.3 on 2022-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroClientes', '0002_alter_cliente_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apelido',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
